micronaut:
  server:
    port: 8089
  application:
    name: pixRest
#configuracoes GRPC
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'
#configuracoes do timestamp
jackson:
  serialization:
    writeDatesAsTimestamps: false